name: tiny_computer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.100+20250912

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  avnc_flutter:
    git:
      url: https://github.com/tiny-computer/avnc_flutter.git
      ref: 4008565259f88fe4613b885979f79e439bc5a420
  clipboard: ^2.0.2
  device_info_plus: ^11.5.0
  dynamic_color: ^1.8.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_pty: ^0.4.2
  http: ^1.5.0
  intl: any
  network_info_plus: ^6.1.4
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  retry: ^3.1.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  wakelock_plus: ^1.3.2
  webview_flutter: ^4.13.0
  x11_flutter:
    git:
      url: https://github.com/tiny-computer/x11_flutter.git
      ref: 3b92b515b1ebc32c93e18e8b3a2983656713e4dd
  xterm: ^4.0.0

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - images/icon.png
